### ISSUE TITLE
The player name problem

### ISSUE THREAD

**Issue by rushlet** [nassosstylianou/football-transfer-window-analysis#1]
https://github.com/nassosstylianou/football-transfer-window-analysis/blob/5338f13b0a0dea23fec61d5850f069cbaff47005/js/main.js#L43-L48
Are you sure that you're getting the name of the first player and not the last player? I think what's happening is that the contents of the div are being rewritten every time it goes over the `$.each` loop - so you're left with only the last one. It looks like it works in the console because it doesn't overwrite what's in the console, it keeps the history. 

https://github.com/nassosstylianou/football-transfer-window-analysis/blob/5338f13b0a0dea23fec61d5850f069cbaff47005/js/main.js#L50-L55
I'm surprised this is doing each one letter by letter, but I reckon it's because you've got a for loop within the each loop. So `value.player_name` must equal a name and `value.player_name[i]` must equal a letter?  It gets all the names in the end because you are using `$('#playerNames').append` rather than `$("#playerNames").html`

**Comment by nassosstylianou** [comment]
Yep, looks like using .append instead of .html solves the issue, as I was overwriting the previous name each time. Fixed!
